INSERT INTO seats (id, seat_number, reserved, booked)
SELECT id, id, 1, 1 
FROM (
	SELECT	1	AS	id	UNION	ALL
	SELECT	2	AS	id	UNION	ALL
	SELECT	3	AS	id	UNION	ALL
	SELECT	4	AS	id	UNION	ALL
	SELECT	5	AS	id	UNION	ALL
	SELECT	6	AS	id	UNION	ALL
	SELECT	7	AS	id	UNION	ALL
	SELECT	8	AS	id	UNION	ALL
	SELECT	9	AS	id	UNION	ALL
	SELECT	10	AS	id	UNION	ALL
	SELECT	11	AS	id	UNION	ALL
	SELECT	12	AS	id	UNION	ALL
	SELECT	13	AS	id	UNION	ALL
	SELECT	14	AS	id	UNION	ALL
	SELECT	15	AS	id	UNION	ALL
	SELECT	16	AS	id	UNION	ALL
	SELECT	17	AS	id	UNION	ALL
	SELECT	18	AS	id	UNION	ALL
	SELECT	19	AS	id	UNION	ALL
	SELECT	20	AS	id	UNION	ALL
	SELECT	21	AS	id	UNION	ALL
	SELECT	22	AS	id	UNION	ALL
	SELECT	23	AS	id	UNION	ALL
	SELECT	24	AS	id	UNION	ALL
	SELECT	25	AS	id	UNION	ALL
	SELECT	26	AS	id	
) AS seq;

INSERT INTO seats (id, seat_number, reserved, booked)
SELECT id, id, 0, 0 
FROM (
	SELECT	27	AS	id	UNION	ALL
	SELECT	28	AS	id	
) AS seq;

INSERT INTO seats (id, seat_number, reserved, booked)
SELECT id, id, 1, 1 
FROM (
	SELECT	29	AS	id	UNION	ALL
	SELECT	30	AS	id	UNION	ALL
	SELECT	31	AS	id	UNION	ALL
	SELECT	32	AS	id	UNION	ALL
	SELECT	33	AS	id	UNION	ALL
	SELECT	34	AS	id	UNION	ALL
	SELECT	35	AS	id	UNION	ALL
	SELECT	36	AS	id	UNION	ALL
	SELECT	37	AS	id	UNION	ALL
	SELECT	38	AS	id	UNION	ALL
	SELECT	39	AS	id	UNION	ALL
	SELECT	40	AS	id	
) AS seq;